import type { Track } from "./types";

export const DC_TRACKS: Track[] = [
  // ── WASHINGTON DC — DPR PUBLIC FACILITIES ────────────────────────────────
  {
    id: "dc-1",
    name: "Maury Wills Field (Banneker Premier Athletic Field)",
    lat: 38.921613,
    lon: -77.023221,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "The premier public track in DC, operated by the DC Department of Parks & Recreation at 801 Barry Place NW near Shaw. A 3-lane, 400m lit track — one of the few in the city open all day and lit at night. Named for baseball legend Maury Wills.",
    surface: "Synthetic",
    lanes: 3,
    lighting: true,
    hours: null,
    publicHours: "Open daily — dawn to dusk (often open later due to lighting)",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Washington DC", "Shaw", "DPR", "lit", "public", "3 lanes", "400m"],
  },
  {
    id: "dc-2",
    name: "Benjamin Banneker High School Track",
    lat: 38.911646,
    lon: -77.026222,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at the new Banneker HS campus in Shaw (opened 2021). DC Department of Parks & Recreation manages public access on weekends. Entrances off Rhode Island Ave and 11th Street.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Sat–Sun 9am–5pm (public access per DCPS/DPR agreement)",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Shaw", "DCPS", "school track"],
  },
  {
    id: "dc-3",
    name: "Cardozo Education Campus Track",
    lat: 38.921083,
    lon: -77.028435,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at Cardozo Education Campus at 13th and Clifton St NW in Columbia Heights. Open to the public during school days early mornings (6–8am) and evenings. Access depends on maintenance staff opening the gate — call ahead or check for a nearby open entry.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "School days: 6–8am and evenings; weekends/vacations: variable — check ahead",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Columbia Heights", "DCPS", "lit", "school track"],
  },
  {
    id: "dc-4",
    name: "Dunbar High School Track",
    lat: 38.908069,
    lon: -77.014379,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track at the historic Dunbar High School at 101 N Street NW in Truxton Circle. One of the largest tracks in the district. Reported closed on weekends — weekday access during non-school hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Weekday non-school hours; closed weekends",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Truxton Circle", "DCPS", "8 lanes", "school track"],
  },
  {
    id: "dc-5",
    name: "Hotchkiss Field",
    lat: 38.906863,
    lon: -76.991745,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track at Hotchkiss Field off Lincoln Circle in Ivy City, NE DC. A DPR facility open to the public — visit reports confirm it's accessible and typically uncrowded.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Likely open during park hours — dawn to dusk",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Washington DC", "Ivy City", "Northeast DC", "DPR", "8 lanes"],
  },
  {
    id: "dc-6",
    name: "Georgetown Community Track",
    lat: 38.913543,
    lon: -77.074871,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "A 320m (non-standard) synthetic 4-lane community track on 39th Street NW in Burleith, Georgetown. Confirmed open to the public. No lighting, but a well-kept neighborhood track used by Georgetown locals.",
    surface: "Synthetic",
    lanes: 4,
    lighting: false,
    hours: null,
    publicHours: "Open to the public — dawn to dusk",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Washington DC", "Georgetown", "Burleith", "community track", "320m", "no lighting"],
  },
  {
    id: "dc-7",
    name: "Eastern Senior High School Track",
    lat: 38.891471,
    lon: -76.979489,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "7-lane synthetic track at Eastern Senior High School in Kingman Park, NE DC. Community access reported outside school hours.",
    surface: "Synthetic",
    lanes: 7,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Kingman Park", "Northeast DC", "DCPS", "school track"],
  },
  {
    id: "dc-8",
    name: "Langston Track",
    lat: 38.901046,
    lon: -76.969411,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "9-lane synthetic track in the Langston neighborhood of NE DC, near the Anacostia River. Located along M Street NE on the Langston Golf Course campus.",
    surface: "Synthetic",
    lanes: 9,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — confirm locally",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Langston", "Northeast DC", "9 lanes"],
  },
  {
    id: "dc-9",
    name: "H.D. Woodson High School Track",
    lat: 38.896864,
    lon: -76.923823,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track at H.D. Woodson High School in Grant Park, Far NE DC. Near the Marvin Gaye Trail and Anacostia River. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Grant Park", "Northeast DC", "DCPS", "8 lanes", "school track"],
  },
  {
    id: "dc-10",
    name: "Kenilworth Track",
    lat: 38.908033,
    lon: -76.945609,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit 400m synthetic track in the Mayfair neighborhood of NE DC, near the Anacostia River Trail and Kenilworth Aquatic Gardens. Good access from the trail corridor.",
    surface: "Synthetic",
    lanes: null,
    lighting: true,
    hours: null,
    publicHours: "Likely open during park hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Mayfair", "Northeast DC", "lit", "near trail"],
  },
  {
    id: "dc-11",
    name: "Theodore Roosevelt High School Track",
    lat: 38.942380,
    lon: -77.027428,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at Theodore Roosevelt High School on Georgia Avenue NW in Petworth. Open to the public outside school hours; no lighting.",
    surface: "Synthetic",
    lanes: null,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Petworth", "DCPS", "school track", "no lighting"],
  },
  {
    id: "dc-12",
    name: "Wilson High School Track",
    lat: 38.949474,
    lon: -77.076762,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "4-lane synthetic track at Wilson High School in Tenleytown/Friendship Heights. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 4,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Tenleytown", "Friendship Heights", "DCPS", "school track"],
  },
  {
    id: "dc-13",
    name: "Ballou STAY High School Track",
    lat: 38.839813,
    lon: -77.001897,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track at Ballou STAY High School in Congress Heights, SE DC. Community access reported outside school hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Congress Heights", "Southeast DC", "DCPS", "8 lanes", "school track"],
  },
  {
    id: "dc-14",
    name: "Anacostia High School Track",
    lat: 38.869838,
    lon: -76.984163,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Anacostia High School in Fairlawn, SE DC. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Fairlawn", "Southeast DC", "Anacostia", "DCPS", "school track"],
  },
  {
    id: "dc-15",
    name: "Archbishop Carroll High School Track",
    lat: 38.941282,
    lon: -77.007543,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "400m track at Archbishop Carroll High School near Fort Drive NE in the Fort Totten / Pleasant Hill area of NE DC.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — call ahead to confirm",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Fort Totten", "Northeast DC", "school track"],
  },
  {
    id: "dc-32",
    name: "Beauvoir School Track",
    lat: 38.929049,
    lon: -77.067558,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Beauvoir School (the elementary school of Washington National Cathedral) at 3500 Woodley Road NW in the Cathedral Heights area. Access unlisted — community members sometimes use it outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — confirm with school",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Cleveland Park", "Cathedral Heights", "school track"],
  },
  {
    id: "dc-33",
    name: "Greene Stadium",
    lat: 38.925607,
    lon: -77.020781,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "400m track at William H. Greene Stadium on 5th Street NW near the McMillan Filter Plant in the Bloomingdale neighborhood. Access unlisted — community members report occasional access.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — verify locally",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Bloomingdale", "McMillan", "stadium"],
  },
  {
    id: "dc-34",
    name: "Cleveland Park Track (37th St NW)",
    lat: 38.939876,
    lon: -77.073114,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Running track at 3868 37th Street NW in Cleveland Park. Exact facility name not confirmed — likely associated with a school or community field in the Cathedral/Cleveland Park corridor.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — verify locally",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Cleveland Park", "school track"],
  },
  {
    id: "dc-29",
    name: "McKinley Technology High School Track",
    lat: 38.913854,
    lon: -77.005733,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Large synthetic track oval at McKinley Technology High School / McKinley Technology Education Campus in Eckington, NE DC, between T Street and R Street NE. Reported under construction as of late 2025 — verify access before visiting.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Temporarily closed — verify before visiting",
    publicAccessType: "closed",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Eckington", "Northeast DC", "DCPS", "school track"],
  },
  // ── ARLINGTON, VIRGINIA ───────────────────────────────────────────────────
  {
    id: "dc-16",
    name: "Greenbrier Park Track",
    lat: 38.900182,
    lon: -77.140675,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "One of three official public tracks in Arlington County, maintained by Arlington Parks & Recreation. Opens at sunrise, closes at dark. Closed only during high school varsity games, track meets, and county-sponsored events.",
    surface: "Synthetic",
    lanes: null,
    lighting: false,
    hours: null,
    publicHours: "Sunrise to dark (closed during varsity games and track meets)",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Arlington", "Virginia", "Arlington County Parks", "public", "community track"],
  },
  {
    id: "dc-17",
    name: "Robert A. Evans Memorial Stadium (Wakefield HS)",
    lat: 38.848708,
    lon: -77.110029,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Robert A. Evans Memorial Stadium at Wakefield High School, South Arlington. One of Arlington County's three officially public outdoor tracks. Opens 7am, closes at dark. Closed during high school games and meets.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "7am to dark (closed during high school games and meets)",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Arlington", "Virginia", "Barcroft", "South Arlington", "Arlington County Parks", "public"],
  },
  {
    id: "dc-18",
    name: "Washington-Liberty HS Track (War Memorial Stadium)",
    lat: 38.886475,
    lon: -77.110210,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at Washington-Liberty High School (War Memorial Stadium) in North Arlington. One of Arlington County's three officially public outdoor tracks. Opens 7am, closes at dark. Closed during high school games and meets.",
    surface: "Synthetic",
    lanes: null,
    lighting: false,
    hours: null,
    publicHours: "7am to dark (closed during high school games and meets)",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Arlington", "Virginia", "North Arlington", "Arlington County Parks", "public"],
  },
  // ── ALEXANDRIA, VIRGINIA ──────────────────────────────────────────────────
  {
    id: "dc-19",
    name: "Alexandria City High School Track",
    lat: 38.823250,
    lon: -77.086283,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "7-lane synthetic track at Alexandria City High School (formerly T.C. Williams) at 3330 King Street in Alexandria. Community access outside school hours. School was renamed in 2020.",
    surface: "Synthetic",
    lanes: 7,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Alexandria", "Virginia", "school track", "7 lanes"],
  },
  {
    id: "dc-40",
    name: "Episcopal High School Track",
    lat: 38.826682,
    lon: -77.099748,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Episcopal High School on West Braddock Road in Alexandria. A well-kept private school track in the Brad Lee neighborhood.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — confirm with school",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Alexandria", "Virginia", "school track", "private school"],
  },
  {
    id: "dc-41",
    name: "St. Stephen's & St. Agnes Upper School Track",
    lat: 38.818762,
    lon: -77.101175,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at St. Stephen's & St. Agnes Upper School on North Gaillard Street in Alexandria. Confirmed community-friendly — visit reports say it's been accessible for years despite being a private school.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours — community-friendly",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Alexandria", "Virginia", "school track", "private school", "community-friendly"],
  },
  {
    id: "dc-42",
    name: "Francis C. Hammond Middle School Track",
    lat: 38.808900,
    lon: -77.116600,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Track at Francis C. Hammond Middle School at 4646 Seminary Road in Alexandria City. Community access outside school hours.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Alexandria", "Virginia", "school track"],
  },
  // ── MONTGOMERY COUNTY, MARYLAND ──────────────────────────────────────────
  {
    id: "dc-20",
    name: "Bethesda-Chevy Chase High School Track",
    lat: 38.987719,
    lon: -77.089237,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at B-CC High School in Bethesda, Montgomery County. Community access outside school hours.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Bethesda", "Maryland", "Montgomery County", "school track"],
  },
  {
    id: "dc-21",
    name: "Takoma Academy Track",
    lat: 38.992187,
    lon: -76.996350,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "400m track at Takoma Academy (private school) in Takoma Park / Silver Spring, just over the DC line into Montgomery County.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — confirm with school",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Silver Spring", "Takoma Park", "Maryland", "Montgomery County", "school track"],
  },
  {
    id: "dc-22",
    name: "Silver Spring International Middle School Track",
    lat: 39.001097,
    lon: -77.012636,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "400m asphalt track at Silver Spring International Middle School in Montgomery Hills, just over the DC line. Confirmed open to the public — often busy with families and neighborhood runners. Located along the Sligo Creek Trail corridor.",
    surface: "Asphalt",
    lanes: null,
    lighting: false,
    hours: null,
    publicHours: "Open to the public — dawn to dusk",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["asphalt", "Silver Spring", "Maryland", "Montgomery County", "public", "near trail"],
  },
  {
    id: "dc-23",
    name: "Montgomery Blair High School Track",
    lat: 39.017313,
    lon: -77.013885,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at one of the DC area's largest high schools in Silver Spring. Community access available evenings during the summer and outside school hours per MCPS policy.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Evenings 7–9pm (summer); likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Silver Spring", "Maryland", "Montgomery County", "school track"],
  },
  {
    id: "dc-31",
    name: "St. Albans School Track",
    lat: 38.929032,
    lon: -77.067551,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Track on the lower athletic fields of St. Albans School on the Cathedral Close, near the Washington National Cathedral. Private school track — access not publicly confirmed, call ahead.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — call ahead to confirm",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Cleveland Park", "Cathedral Heights", "school track", "National Cathedral"],
  },
  {
    id: "dc-30",
    name: "American University Track",
    lat: 38.937562,
    lon: -77.091794,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track on the American University campus in Tenleytown/American University Park. Generally open to the public — confirmed accessible by community members, but closed when AU teams are practicing.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside team practice hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Washington DC", "Tenleytown", "American University Park", "university track", "6 lanes"],
  },
  // ── FAIRFAX COUNTY, VIRGINIA ──────────────────────────────────────────────
  {
    id: "dc-25",
    name: "Langley High School Track",
    lat: 38.951721,
    lon: -77.166108,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit 6-lane synthetic track at Langley High School in McLean, Fairfax County. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "McLean", "Virginia", "Fairfax County", "lit", "school track"],
  },
  {
    id: "dc-26",
    name: "Falls Church High School Track",
    lat: 38.861009,
    lon: -77.209369,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Falls Church High School in West Falls Church, Fairfax County. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Falls Church", "Virginia", "Fairfax County", "school track"],
  },
  {
    id: "dc-27",
    name: "Annandale High School Track",
    lat: 38.823397,
    lon: -77.210110,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit 6-lane synthetic track at Annandale High School in Annandale, Fairfax County. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Annandale", "Virginia", "Fairfax County", "lit", "school track"],
  },
  {
    id: "dc-35",
    name: "Yorktown High School Track",
    lat: 38.900188,
    lon: -77.140652,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Yorktown High School on 27th Street North in the Highland Park neighborhood of Arlington. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Arlington", "Virginia", "Highland Park", "school track"],
  },
  {
    id: "dc-39",
    name: "Meridian High School Track",
    lat: 38.899004,
    lon: -77.191716,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at Meridian High School (formerly George Mason High School) in Falls Church City, Virginia. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Falls Church", "Virginia", "Falls Church City", "school track"],
  },
  {
    id: "dc-36",
    name: "McLean High School Track",
    lat: 38.924674,
    lon: -77.185870,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at McLean High School in West McLean, Fairfax County. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "McLean", "Virginia", "Fairfax County", "school track"],
  },
  {
    id: "dc-37",
    name: "Walter Johnson High School Track",
    lat: 39.023931,
    lon: -77.130162,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track at Walter Johnson High School in North Bethesda / Rock Spring, Montgomery County. Community access outside school hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "North Bethesda", "Maryland", "Montgomery County", "8 lanes", "school track"],
  },
  {
    id: "dc-38",
    name: "Bladensburg High School Track",
    lat: 38.942827,
    lon: -76.919234,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Track at Bladensburg High School in Bladensburg, Prince George's County — just 8 miles northeast of downtown DC.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Bladensburg", "Maryland", "Prince George's County", "school track"],
  },
  {
    id: "dc-28",
    name: "West Potomac High School Track",
    lat: 38.772712,
    lon: -77.073567,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "6-lane synthetic track at West Potomac High School in the Belle Haven area of Fairfax County, near the Potomac River. Confirmed community-friendly — visitors report easy access on weekdays and weekends.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours — community-friendly",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Belle Haven", "Virginia", "Fairfax County", "school track"],
  },
];
