import type { Track, Review } from "./types";

// Real NYC public tracks — coordinates sourced from runtrack.run (OpenStreetMap data)
export const MOCK_TRACKS: Track[] = [
  {
    // Source: runtrack.run/track/icahn-stadium
    // World Athletics Class 1 certified; Mondo Super X Performance surface
    // Community Track Nights offered on select evenings; check nyrr.org for schedule
    id: "mock-1",
    reviewSummary: "A world-class facility by any measure. Runners consistently praise the fast, well-maintained Mondo Super X surface and the authentic stadium atmosphere. The main drawback is limited drop-in access — the track is only open during scheduled Community Track Nights, so it rewards planners rather than spontaneous visitors.",
    name: "Icahn Stadium",
    lat: 40.79327,
    lon: -73.92546,
    distance: 0.0,
    rating: 4.8,
    reviewCount: 214,
    surface: "Mondo Super X Performance",
    lanes: 8,
    lighting: true,
    hours: "Event-based; Community Track Nights available",
    publicHours: "Community Track Nights only — select Thursday evenings in summer, starting 6 pm, free, ages 18+. Track is NOT open for general drop-in use. Check randallsisland.org/events for upcoming dates.",
    publicAccessType: "conditional",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "floodlit", "field events", "World Athletics Class 1", "Randalls Island"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/riverbank-state-park
    // Rooftop facility above the Henry Hudson Pkwy; synthetic surface, 8 lanes
    id: "mock-2",
    reviewSummary: "Widely considered one of NYC's most underrated tracks. The rooftop setting above the West Side Highway eliminates street noise, the 8-lane synthetic surface stays in solid shape, and crowds are notably thin even on weekday evenings. Regulars recommend arriving before 9 am on weekdays for the quietest sessions.",
    name: "Riverbank State Park Track",
    lat: 40.82493,
    lon: -73.95705,
    distance: 0.0,
    rating: 4.5,
    reviewCount: 163,
    surface: "Synthetic",
    lanes: 8,
    lighting: true,
    hours: "6 am – 11 pm daily",
    publicHours: "Open to the public daily, 6 am–11 pm. No reservation required. Weekday mornings (before 9 am) are the least crowded.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "floodlit", "rooftop", "Hudson River views", "Harlem"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/john-v-lindsay-east-river-park-track
    // Rubber Coated All Weather surface; 8 lanes; no lighting
    // Closed for ESCR flood-protection reconstruction — check NYC Parks before visiting
    id: "mock-3",
    reviewSummary: "Currently closed for ESCR flood-protection reconstruction with no firm reopening date. Pre-closure reviews were mixed — the rubber surface had visible wear and no lighting limited evening use — but the waterfront location was a genuine draw. Worth monitoring, not worth visiting until NYC Parks confirms it has reopened.",
    name: "John V. Lindsay East River Park Track",
    lat: 40.72170,
    lon: -73.97340,
    distance: 0.0,
    rating: 3.6,
    reviewCount: 87,
    surface: "Rubber Coated All Weather",
    lanes: 6,
    lighting: false,
    hours: "6 am – 10 pm (check access — under reconstruction)",
    publicHours: "Currently closed for ESCR flood-protection reconstruction. Expected to reopen — check nyc.gov/parks or call 311 for current status before visiting.",
    publicAccessType: "closed",
    access: "public",
    cost: "Free",
    tags: ["6-lane", "400m", "no lighting", "waterfront", "Lower East Side", "under renovation"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/mccarren-park-track
    // Rubber surface; 8 lanes; floodlit for evening use
    id: "mock-4",
    reviewSummary: "A workhorse of a track in one of Brooklyn's most active neighborhoods. The rubber surface is in reliable shape and the floodlights make weeknight workouts viable year-round. Expect company — club runners dominate weekday evenings, so weekend mornings or early weekdays offer the most room to move.",
    name: "McCarren Park Track",
    lat: 40.72001,
    lon: -73.95127,
    distance: 0.0,
    rating: 4.2,
    reviewCount: 119,
    surface: "Rubber",
    lanes: 8,
    lighting: true,
    hours: "6 am – 10 pm daily",
    publicHours: "Open to the public daily, 6 am–10 pm. No reservation required. Can get busy with club runners on weekday evenings; weekday mornings and weekend afternoons are typically more open.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "floodlit", "Williamsburg", "Brooklyn"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/astoria-park
    // Mondo surface; 8 lanes; renovated 2019 via $13.65M Anchor Parks program
    // Lights on until 10 pm
    id: "mock-5",
    reviewSummary: "One of the best open-access tracks in the five boroughs. The Mondo surface from the 2019 Anchor Parks renovation is fast and in excellent condition, and the views of Hell Gate and the Triborough Bridge make every workout feel like an event. Rarely overcrowded — even weekend mornings have room to work.",
    name: "Astoria Park Track",
    lat: 40.77678,
    lon: -73.92583,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 76,
    surface: "Mondo",
    lanes: 8,
    lighting: true,
    hours: "Dawn – 10 pm",
    publicHours: "Open to the public dawn–10 pm, every day. No reservation required. First come, first served — generally uncrowded outside of weekend mornings.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "floodlit", "renovated 2019", "Hell Gate views", "Queens"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/macombs-dam-park
    // Joseph Yancey Track and Field; Olympic-quality Mondo-type surface; 8 lanes
    // Adjacent to Yankee Stadium, South Bronx
    id: "mock-6",
    reviewSummary: "A solid Bronx option anchored by a quality Mondo surface and an iconic location next to Yankee Stadium. No lighting limits usable hours to daylight, and school and youth teams occupy the track on weekday afternoons during the school year. Best for weekend mornings or early weekday sessions before teams arrive.",
    name: "Macombs Dam Park Track",
    lat: 40.82804,
    lon: -73.92903,
    distance: 0.0,
    rating: 3.8,
    reviewCount: 51,
    surface: "Mondo",
    lanes: 8,
    lighting: false,
    hours: "Dawn – dusk",
    publicHours: "Open to the public dawn–dusk. School and youth teams may use the track on weekday mornings and afternoons during the school year. Weekends and weekday evenings are most reliably open for general public use.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "Joseph Yancey Track", "South Bronx", "next to Yankee Stadium"],
    osmType: "way",
    osmId: 0,
  },

  // ── Additional tracks across the five boroughs ──

  {
    // Source: runtrack.run/track/van-cortlandt-stadium
    // WPA-built stadium (1939); track reconstructed 1998 with all-weather rubberized surface
    // Synthetic turf infield installed 2009; home to cross-country and track meets
    id: "mock-7",
    reviewSummary: "The WPA-era grandstands give this Riverdale track real character, and the rubberized surface holds up well despite heavy cross-country use. No lighting makes it a daytime-only destination, and school teams are frequently on the track on weekday afternoons in fall and spring. Weekend and early-morning sessions are reliably open.",
    name: "Van Cortlandt Stadium",
    lat: 40.88813,
    lon: -73.89760,
    distance: 0.0,
    rating: 4.2,
    reviewCount: 98,
    surface: "Rubberized synthetic",
    lanes: 8,
    lighting: false,
    hours: "Dawn – 10 pm",
    publicHours: "Open to the public dawn–10 pm. School and college cross-country teams frequently use the track on weekday afternoons during the school year. Weekends and early weekday mornings are most reliably open for general public use.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "no lighting", "stadium", "WPA-built", "Riverdale", "Bronx"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/soundview-park + NYC Parks Daily Plant announcement
    // Rubberized 400m regulation track with field event areas; lighting confirmed
    // Renovated as part of Soundview Park capital project (Clason Point, Bronx)
    id: "mock-8",
    reviewSummary: "A reliably uncrowded 8-lane track in the Bronx that delivers on the basics: solid rubberized surface, good lighting, and consistent free access. Occasional permitted events can temporarily close it, but for most visits it's first-come, first-served with plenty of room to train.",
    name: "Soundview Park Track",
    lat: 40.81783,
    lon: -73.87281,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 44,
    surface: "Rubberized synthetic",
    lanes: 8,
    lighting: true,
    hours: "Dawn – 10 pm",
    publicHours: "Open to the public dawn–10 pm. No formal reservation system — first come, first served. Generally uncrowded; occasional permitted events may limit access.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "floodlit", "field events", "Clason Point", "Bronx"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/roy-wilkins-park + NYC Parks
    // 400m synthetic track; 8 lanes; confirmed lighting; park closes 9 pm
    // Southeast Queens — rated "great" on runtrack.run
    id: "mock-9",
    reviewSummary: "The go-to track for Southeast Queens, consistently praised for its 8-lane layout, well-maintained synthetic surface, and lights that run until 9 pm. Accessible by car with parking nearby, and weekday mornings tend to be the quietest window for focused workouts.",
    name: "Roy Wilkins Park Track",
    lat: 40.68824,
    lon: -73.77334,
    distance: 0.0,
    rating: 4.3,
    reviewCount: 67,
    surface: "Synthetic",
    lanes: 8,
    lighting: true,
    hours: "Dawn – 9 pm",
    publicHours: "Open to the public dawn–9 pm. No reservation required. Weekday mornings and weekends are typically the least crowded times for public runners.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["8-lane", "400m", "floodlit", "Jamaica", "SE Queens"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/forest-park + Forest Park Trust
    // 400m track at Victory Field; 6 lanes; no lighting; public access confirmed July 2024
    // Note: puddles can form in lanes after heavy rainfall
    id: "mock-10",
    reviewSummary: "A quiet and reliably uncrowded track in Woodhaven. The synthetic surface is functional, though reviewers flag drainage issues in the inner lanes after heavy rain. No lighting makes it a daytime-only spot, and the 6-lane layout means less room during busier weekend afternoons.",
    name: "Forest Park Track (Victory Field)",
    lat: 40.70137,
    lon: -73.85253,
    distance: 0.0,
    rating: 3.7,
    reviewCount: 39,
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: "Dawn – dusk",
    publicHours: "Open to the public dawn–dusk. No reservation system — first come, first served. Generally uncrowded; puddles may form in lanes after heavy rain.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["6-lane", "400m", "no lighting", "Victory Field", "Woodhaven", "Queens"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/wingate-park + PPTC Brooklyn Tracks article
    // 320m rubber track (non-standard length — 1.25 laps ≈ 400m); 6 lanes
    // Open 6 am – midnight; near 2/5 subway lines at Winthrop St
    id: "mock-11",
    reviewSummary: "Easy access off the 2 train makes this Crown Heights track a solid neighborhood option. The non-standard 320m loop is an adjustment — most runners count 5 laps as 1600m — and school teams occupy the track on weekday afternoons during the school year. The rubber surface is in decent condition and the late closing time of midnight is a genuine standout.",
    name: "Wingate Park Track",
    lat: 40.65825,
    lon: -73.94408,
    distance: 0.0,
    rating: 3.9,
    reviewCount: 55,
    surface: "Rubber",
    lanes: 6,
    lighting: null,
    hours: "6 am – midnight",
    publicHours: "Open to the public 6 am–midnight. Adjacent to the High School for Public Service — school teams use the track on weekday mornings and afternoons during the school year. Best times for open public use: after 3 pm on weekdays, or anytime on weekends.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["6-lane", "320m", "non-standard length", "Crown Heights", "Brooklyn"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: oceanbreezenyc.org + NYC Parks + Sage & Coombe Architects project page
    // State-of-the-art INDOOR 200m hydraulically-banked competition track
    // Convertible 6–8 lanes; Mondo surface; hosts national and world-record meets
    // NYC Parks Rec Center — annual membership required ($25 adults / free under 18 & 65+)
    // Located in Ocean Breeze neighborhood (eastern shore, SI) — overlooks Verrazano Bridge
    id: "mock-12",
    reviewSummary: "The most technically impressive public-access track in the five boroughs — a Mondo-surfaced, hydraulically-banked 200m indoor oval built for elite competition. At $25 per year (free under 18 and over 65), membership is extraordinary value. The main limitation is meet-day closures, which can be frequent in winter; always call ahead before making the trip.",
    name: "Ocean Breeze Athletic Complex",
    lat: 40.582966,
    lon: -74.075089,
    distance: 0.0,
    rating: 4.9,
    reviewCount: 182,
    surface: "Mondo",
    lanes: 6,
    lighting: true,
    hours: "Mon–Thu 5:30 am – 7:30 pm · Fri–Sun 6:30 am – 1:30 pm",
    publicHours: "Requires an annual membership ($25 adults · free under 18 & 65+). Once a member, open recreation runs Mon–Thu 5:30 am–7:30 pm and Fri–Sun 6:30 am–1:30 pm. Track closes entirely during competition meets — call ahead: (718) 351-7923.",
    publicAccessType: "conditional",
    access: "public",
    cost: "$25/year membership (free under 18 & 65+)",
    tags: ["6-lane", "200m indoor", "indoor", "banked", "Mondo", "competition", "South Beach", "Staten Island"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/the-armory + armory.nyc + The Armory Foundation
    // 200m INDOOR Mondo Super X Performance track; 6 lanes; $10/visit open lap admission
    // Hosts ~100 meets/year including national championships; open to general public for open laps
    // Coordinates from runtrack.run (OpenStreetMap): 216 Fort Washington Ave, Washington Heights
    id: "mock-13",
    reviewSummary: "One of the most storied indoor tracks in the country, with a Mondo Super X surface where world records have been set. The $10 per-visit fee is reasonable for the quality, but the heavy competition calendar — roughly 100 meets per year, concentrated October through March — means many training days are unavailable to the public. Best accessed on weekday mornings outside of meet season.",
    name: "The Armory Track & Field Center",
    lat: 40.84218,
    lon: -73.94141,
    distance: 0.0,
    rating: 4.7,
    reviewCount: 311,
    surface: "Mondo Super X Performance",
    lanes: 6,
    lighting: true,
    hours: "Mon–Fri 9 am – 7 pm · Sat–Sun 9 am – 5 pm",
    publicHours: "Pay-to-use: $10/visit or $275 season pass for adults. Open training available Mon–Thu — but the track is closed to the public on meet days (~100 meets per year, primarily Oct–Mar). Always call ahead to confirm open laps are available: (212) 923-1803.",
    publicAccessType: "conditional",
    access: "public",
    cost: "$10/visit",
    tags: ["6-lane", "200m indoor", "indoor", "Mondo", "competition", "Washington Heights", "Manhattan"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: Wikipedia + NYC Parks + runtrack.run/track/williamsbridge-playground
    // Historic WPA-built oval (1937) — 400m track surrounds a soccer/football field at the sunken reservoir bottom
    // 4 lanes; synthetic surface; one of the Bronx's best-kept open-air track secrets
    // National Register of Historic Places (2015); fully free, no permit needed
    id: "mock-14",
    reviewSummary: "A beloved Bronx institution and genuine hidden gem. Built on the floor of the old Williamsbridge Reservoir, the oval's unique below-grade setting creates a quiet, enclosed atmosphere that regular users find deeply satisfying. Free, open daily, and lit until 10 pm — the only real trade-off is the 4-lane layout.",
    name: "Williamsbridge Oval",
    lat: 40.87765,
    lon: -73.87735,
    distance: 0.0,
    rating: 4.5,
    reviewCount: 88,
    surface: "Synthetic",
    lanes: 4,
    lighting: true,
    hours: "Daily 6 am – 10 pm",
    publicHours: "Fully open to the public — no fee, no permit required, any day during park hours. A beloved Norwood/Bronx training spot with a uniquely historic oval layout built on the old Williamsbridge Reservoir.",
    publicAccessType: "open",
    access: "yes",
    cost: null,
    tags: ["400m", "synthetic", "4-lane", "free", "Bronx", "historic", "WPA"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/thomas-jefferson-park + NYC Parks + Wikipedia
    // Public NYC Parks track in East Harlem, Manhattan — 1st Ave & 111th–114th St
    // Synthetic surface; free drop-in daily; one of the few Manhattan-side tracks
    id: "mock-15",
    reviewSummary: "Widely regarded as the most accessible free track in Manhattan. The synthetic surface is reliable, the lights extend usable hours into the evening, and the East River location adds a pleasant backdrop. Weekday mornings before the park fills are the preferred window for focused training.",
    name: "Thomas Jefferson Park Track",
    lat: 40.79432,
    lon: -73.93628,
    distance: 0.0,
    rating: 4.2,
    reviewCount: 76,
    surface: "Synthetic",
    lanes: null,
    lighting: true,
    hours: "Daily 6 am – 10 pm",
    publicHours: "Fully open to the public — no fee or permit needed. NYC Parks facility, free drop-in any day during park hours. One of the only freely accessible running tracks directly on the Manhattan side of the river.",
    publicAccessType: "open",
    access: "yes",
    cost: null,
    tags: ["synthetic", "free", "Manhattan", "East Harlem", "NYC Parks"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/juniper-valley-park + NYC Parks + QNS.com
    // 400m, 6-lane synthetic track in Middle Village, Queens
    // Fully rebuilt Nov 2022 ($5.25M project) — new surface, turf field, adult fitness area
    // Free NYC Parks facility, open dawn to dusk
    id: "mock-16",
    reviewSummary: "Rebuilt from the ground up in 2022, this Middle Village track is in some of the best surface condition of any free NYC Parks facility. The 6-lane layout and clean synthetic surface get consistently strong marks, and the surrounding park makes it a pleasant destination. No confirmed lighting, so daytime visits are the safe bet.",
    name: "Juniper Valley Park Track",
    lat: 40.71990,
    lon: -73.88427,
    distance: 0.0,
    rating: 4.4,
    reviewCount: 91,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Dawn to dusk",
    publicHours: "Fully open to the public — no fee or permit required. The track and turf field were completely rebuilt in 2022 and are in excellent condition. Free NYC Parks facility accessible any day during park hours.",
    publicAccessType: "open",
    access: "yes",
    cost: null,
    tags: ["400m", "synthetic", "6-lane", "free", "Queens", "Middle Village", "rebuilt 2022"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/betsy-head-memorial-playground + NYC Parks
    // Synthetic 4-lane track in Brownsville, Brooklyn — public NYC Parks facility
    // Located at 153 Dumont Ave; free drop-in access
    id: "mock-17",
    reviewSummary: "A no-frills community track in Brownsville that earns steady praise for being clean, reliably accessible, and never overcrowded. The 4-lane layout limits simultaneous use, and no confirmed lighting means evening visits are uncertain. Good enough to anchor a local training routine, though not a destination track.",
    name: "Betsy Head Memorial Playground Track",
    lat: 40.66275,
    lon: -73.91388,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 49,
    surface: "Synthetic",
    lanes: 4,
    lighting: null,
    hours: "Daily 6 am – 10 pm",
    publicHours: "Fully open to the public — no fee or permit needed. Free NYC Parks facility in Brownsville, open daily during park hours.",
    publicAccessType: "open",
    access: "yes",
    cost: null,
    tags: ["synthetic", "4-lane", "free", "Brooklyn", "Brownsville"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/aileen-b-ryan-recreational-complex + dailytrackpic.wordpress.com + NYC Parks
    // 400m, 8-lane Mondo track in northeast Bronx at the edge of Pelham Bay Park
    // Built 2004 on site of historic Rice Stadium (1920s); publicly operated by NYC Parks
    // Rated "great" quality; alternating blue/tan Mondo lanes; full field event facilities
    id: "mock-18",
    reviewSummary: "One of the most underrated tracks in the entire city. The 8-lane Mondo surface in alternating blue and tan lanes is competition-grade, the Pelham Bay Park setting is genuinely beautiful, and the track is almost always empty on weekday mornings. Reviewers are unanimous: the trip out to the northeast Bronx is worth it.",
    name: "Aileen B. Ryan Recreational Complex",
    lat: 40.84911,
    lon: -73.82297,
    distance: 0.0,
    rating: 4.6,
    reviewCount: 103,
    surface: "Mondo",
    lanes: 8,
    lighting: null,
    hours: "Daily 6 am – 10 pm",
    publicHours: "Fully open to the public — free NYC Parks facility with no permit required. Part of Pelham Bay Park in the northeast Bronx. Built on the site of the old Rice Stadium, the track has 8 Mondo lanes and is one of the best-kept free tracks in the city.",
    publicAccessType: "open",
    access: "yes",
    cost: null,
    tags: ["400m", "Mondo", "8-lane", "free", "Bronx", "Pelham Bay", "competition-grade"],
    osmType: "way",
    osmId: 0,
  },

  // ── More NYC Parks community tracks ──

  {
    // Source: runtrack.run/track/red-hook-recreation-area + NYC Parks + Red Hook Initiative
    // 400m synthetic track, 8 lanes; 100 Bay St, Red Hook, Brooklyn 11231
    // Closed July 2021 for 18-month resurfacing — fully reopened by early 2023; NYC Parks managed
    id: "mock-37",
    reviewSummary: "Red Hook's best track on paper — 8 wide lanes and a freshly resurfaced synthetic oval — but currently closed. Check NYC Parks for reopening updates before making the trip.",
    name: "Red Hook Recreation Area Track",
    lat: 40.6721,
    lon: -74.0070,
    distance: 0.0,
    rating: 1.5,
    reviewCount: 43,
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: "Currently closed",
    publicHours: "Currently closed — check the NYC Parks website for reopening information.",
    publicAccessType: "closed",
    access: "private",
    cost: "Free",
    tags: ["400m", "synthetic", "8-lane", "Red Hook", "Brooklyn", "NYC Parks", "closed"],
    osmType: "way",
    osmId: 0,
  },

  // ── High school tracks with conditional / unverified public access ──

  {
    // Source: NYC DOE + latitude.to + OpenStreetMap way/46588442
    // 400m track at Abraham Lincoln High School, 2800 Ocean Pkwy, Brighton Beach, Brooklyn 11235
    // Public NYCDOE high school; community access informal — gate often open outside school hours
    id: "mock-35",
    reviewSummary: "A Brighton Beach neighborhood staple for local runners. Being steps from the beach, it has one of the most pleasant surroundings of any high school track in the boroughs. Access is informal — no official open-track policy, but the gate is typically open evenings and weekends. School teams occupy the track on weekday afternoons during the school year, so plan accordingly.",
    name: "Abraham Lincoln High School Track",
    lat: 40.5826,
    lon: -73.9693,
    distance: 0.0,
    rating: 3.7,
    reviewCount: 24,
    surface: "Synthetic",
    lanes: null,
    lighting: false,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access is unconfirmed. As a NYC public school, the gate is often open after school hours and on weekends, but there is no official open-track policy. Avoid weekday afternoons during the school year when athletic programs are active. No lighting, so daytime visits only.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["synthetic", "public school", "Brighton Beach", "Brooklyn", "near beach", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },

  {
    // Source: runtrack.run/track/tottenville-high-school + NYC DOE
    // 400m synthetic track at Staten Island's largest public high school (NYCDOE)
    // Public access unconfirmed — gate is often open evenings and weekends per community reports
    // Located at the southern tip of SI near Princes Bay; call school to verify: 718-668-8800
    id: "mock-23",
    reviewSummary: "The gate is often open evenings and weekends, but community access to this public school track is entirely informal. Locals report consistent weekend access with no issues; others have found it locked for events without warning. The track is functional and convenient for Princes Bay runners — call the school before making a dedicated trip.",
    name: "Tottenville High School Track",
    lat: 40.52956,
    lon: -74.19383,
    distance: 0.0,
    rating: 3.5,
    reviewCount: 14,
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access is unconfirmed. As a NYC public school, the gate is often open after school hours and on weekends, but there is no official open-track policy. Call the school before making the trip: 718-668-8800. Avoid weekday afternoons during the school year when teams are practicing.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "public school", "Staten Island", "Princes Bay", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/st-joseph-by-the-sea-high-school (marked "possibly" open)
    // 400m synthetic, 6 lanes, lit — private Catholic co-ed school in Huguenot, Staten Island
    // 25+ acre sports complex at 5150 Hylan Blvd; community use reported outside school hours
    id: "mock-24",
    reviewSummary: "A 6-lane, lit oval in good condition on a well-kept private school campus. Community use on weekend mornings has been reported positively, but access is at the school's discretion with no formal policy. The lighting is a genuine advantage over most comparable tracks on the island — call ahead before visiting.",
    name: "St. Joseph by the Sea Track",
    lat: 40.52397,
    lon: -74.17550,
    distance: 0.0,
    rating: 3.8,
    reviewCount: 18,
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: "Unconfirmed — possibly accessible non-school hours",
    publicHours: "Public access is unconfirmed but reported as possible outside of school and athletic program hours. Private Catholic school — access is at the school's discretion. Call ahead before visiting: (718) 984-7900. Best bet is weekend mornings when no team events are scheduled.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "floodlit", "private school", "Staten Island", "Huguenot", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/new-dorp-high-school + NYC DOE
    // 400m synthetic, 8 lanes — one of the highest lane counts at any NYC public high school
    // NYCDOE public school in New Dorp, Staten Island; public access unconfirmed
    id: "mock-25",
    reviewSummary: "Eight lanes at a high school track is unusual in NYC, and the extra room is the main draw. The surface shows some wear in the inner lanes but is fully runnable. Gate hours are inconsistent — weekend mornings have generally worked for community runners, though there's no guarantee. No lighting means daytime visits only.",
    name: "New Dorp High School Track",
    lat: 40.57098,
    lon: -74.10625,
    distance: 0.0,
    rating: 3.6,
    reviewCount: 11,
    surface: "Synthetic",
    lanes: 8,
    lighting: false,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access is unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no formal open-track policy. The 8-lane track is one of the widest at any high school in the borough — worth a call to verify: (718) 667-8686. Avoid weekday afternoons during the school year.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "8-lane", "public school", "Staten Island", "New Dorp", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },

  // ── NYC Parks community tracks — Bronx ──

  {
    // Source: nycgovparks.org/parks/st-marys-park + NYRR Open Run + mypacer.com
    // Running track within the 35-acre St. Mary's Park, Mott Haven, South Bronx
    // NYRR hosts Open Run community events here; synthetic surface installed as part of capital improvements
    // Park address: 376 St. Ann's Ave, Bronx NY 10454
    id: "mock-34",
    reviewSummary: "The go-to free track for Mott Haven and the South Bronx. The synthetic surface is in solid shape and the park's 35 acres give the whole experience room to breathe. NYRR hosts Open Run events here periodically, which brings out a friendly community vibe. Consistently easy to access — rarely gated, never overcrowded on weekday mornings.",
    name: "St. Mary's Park Track",
    lat: 40.81137,
    lon: -73.91081,
    distance: 0.0,
    rating: 4.1,
    reviewCount: 58,
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: "6 am – 10 pm",
    publicHours: "Fully open to the public — no fee or permit required. NYC Parks facility in Mott Haven, South Bronx, open daily 6 am–10 pm. NYRR hosts periodic Open Run community events here. No reservation needed for general use.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["synthetic", "free", "Mott Haven", "South Bronx", "NYC Parks", "NYRR Open Run"],
    osmType: "way",
    osmId: 0,
  },

  // ── NYC Parks community tracks ──

  {
    // Source: nycgovparks.org/parks/fort-hamilton-athletic-field + Brooklyn Home Reporter (Aug 2019 reopening)
    // 400m rubber/synthetic track at Bay Ridge's largest public athletic facility; rebuilt 2001
    // Adjacent to Fort Hamilton High School — NYC Parks managed; free public access
    id: "mock-26",
    reviewSummary: "Bay Ridge's premier free outdoor track, fully rebuilt with a synthetic rubber surface and artificial turf infield. The facility is spacious, well-maintained, and almost never overcrowded. School teams use it on weekday afternoons during the school year, so mornings and weekends are the most reliably open windows for public runners.",
    name: "Fort Hamilton HS Athletic Field",
    lat: 40.6267,
    lon: -74.0374,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 38,
    surface: "Rubber synthetic",
    lanes: null,
    lighting: null,
    hours: "Dawn – dusk",
    publicHours: "Open to the public dawn–dusk as a NYC Parks facility. School teams may use the track on weekday afternoons during the school year — weekday mornings and weekends are most reliably open for general public use. No fee or reservation required.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["400m", "rubber", "free", "Bay Ridge", "Brooklyn", "NYC Parks", "turf infield"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: nycgovparks.org/parks/linden-park + runtrack.run/track/linden-park
    // 400m synthetic track, 6 lanes; Linden Park is at 2020 Linden Blvd, East New York, Brooklyn 11207
    // NYC Parks capital project reconstructed synthetic turf field and rubberized track (project 8562)
    id: "mock-28",
    reviewSummary: "A solid 6-lane track in East New York that benefited from a capital reconstruction project. The synthetic surface is in reliable shape, and the park setting on Linden Boulevard makes it a pleasant neighborhood option. Rarely overcrowded — a dependable choice for locals who don't want to travel for a quality surface.",
    name: "Linden Playground Track",
    lat: 40.6592,
    lon: -73.8875,
    distance: 0.0,
    rating: 3.9,
    reviewCount: 29,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Dawn – dusk",
    publicHours: "Fully open to the public — no fee or permit required. NYC Parks facility at Linden Park, open any day during park hours. Track and turf field were reconstructed under a capital project.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "free", "East New York", "Brooklyn", "NYC Parks"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: nycgovparks.org/parks/leon-s-kaiser-park + Kaiser Park Daily Plant (Running Circles around the Competition)
    // 400m track at Kaiser Park, 2903 Neptune Ave, Coney Island, Brooklyn — 26.26-acre waterfront park
    // Replaced older cinder track with modern synthetic surface; public NYC Parks facility
    id: "mock-29",
    reviewSummary: "Kaiser Park's track sits on a sweeping 26-acre waterfront property on the northwestern tip of Coney Island — a genuinely scenic setting for a free neighborhood track. The synthetic surface replaced an old cinder oval and is in solid condition. The ocean breeze can pick up on windy days, but most runners consider that a feature, not a bug.",
    name: "Leon S. Kaiser Playground Track",
    lat: 40.5794,
    lon: -73.9967,
    distance: 0.0,
    rating: 4.1,
    reviewCount: 44,
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: "Dawn – dusk",
    publicHours: "Fully open to the public — no fee or permit required. NYC Parks facility on the waterfront in Coney Island, open any day during park hours. Generally uncrowded.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["400m", "synthetic", "free", "Coney Island", "Brooklyn", "NYC Parks", "waterfront"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: nycgovparks.org/parks/baisley-pond-park + NYC Parks Capital Project 9191
    // Track reconstruction + synthetic turf field + sports lighting — capital project design completed July 2025
    // Located near JFK Airport in Springfield Gardens, Queens; NYRR hosts Open Run events here
    id: "mock-31",
    reviewSummary: "A recently upgraded Queens track near JFK Airport with newly installed sports lighting — one of the few Springfield Gardens facilities to get this treatment. NYRR hosts regular Open Run events here, which gives it an active community feel. Verify the current status of the reconstruction before visiting, as the capital project was finalized in 2025.",
    name: "Baisley Pond Park Track",
    lat: 40.6778,
    lon: -73.7858,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 31,
    surface: "Synthetic",
    lanes: null,
    lighting: true,
    hours: "Dawn – 10 pm",
    publicHours: "Fully open to the public — no fee or permit required. NYC Parks facility in Springfield Gardens, Queens. Recently upgraded with a reconstructed track, synthetic turf field, and sports lighting. NYRR hosts Open Run community events here periodically.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["400m", "synthetic", "floodlit", "free", "Springfield Gardens", "Queens", "NYC Parks", "NYRR Open Run"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: nycgovparks.org/parks/detective-keith-l-williams-park + runtrack.run + NYC Parks Daily Plant
    // 400m synthetic track; 171-43 105th Ave, Hillside, Queens 11433 (Jamaica area)
    // NYC Parks capital project added track & field + tennis courts; full field event facilities
    id: "mock-32",
    reviewSummary: "A well-equipped NYC Parks track in Jamaica, Queens with a full complement of field event facilities. The synthetic surface holds up well and the park is rarely packed, making it a comfortable choice for focused interval training. The Daily Plant announcement at opening called it a hub for Track & Field — it has lived up to that promise.",
    name: "Det. Keith L. Williams Park Track",
    lat: 40.7027,
    lon: -73.7843,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 36,
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: "Dawn – dusk",
    publicHours: "Fully open to the public — no fee or permit required. NYC Parks facility in Hillside, Queens (Jamaica area). Track and field event facilities are open any day during park hours on a first-come, first-served basis.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["400m", "synthetic", "free", "field events", "Hillside", "Jamaica", "Queens", "NYC Parks"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: nycgovparks.org/parks/corporal-thompson-park + runtrack.run/track/corporal-thompson-park + NYC Parks Daily Plant
    // 400m synthetic track, 6 lanes, confirmed lighting; 779 Henderson Ave, West Brighton, Staten Island 10310
    // NYC Parks: "only public outdoor track in the borough" at opening; full field event facilities including steeplechase
    id: "mock-33",
    reviewSummary: "Described at its opening as the only public outdoor track in Staten Island, Corporal Thompson Park is the borough's most fully equipped free track facility. The 6-lane synthetic oval comes with proper field event areas including steeplechase — a genuine rarity at a public NYC Parks site. Floodlights extend usable hours into the evening, and the West Brighton location is accessible from the North Shore.",
    name: "Corporal Thompson Park Track",
    lat: 40.6380,
    lon: -74.1189,
    distance: 0.0,
    rating: 4.3,
    reviewCount: 47,
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: "Dawn – 10 pm",
    publicHours: "Fully open to the public — no fee or permit required. NYC Parks facility in West Brighton, Staten Island. One of the borough's only public outdoor tracks, with 6 lanes and floodlights for evening use. Field event facilities include steeplechase — open daily during park hours.",
    publicAccessType: "open",
    access: "public",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "floodlit", "field events", "steeplechase", "free", "West Brighton", "Staten Island", "NYC Parks"],
    osmType: "way",
    osmId: 0,
  },

  {
    // Source: runtrack.run/track/boys-girls-high-scool + NYC DOE
    // 400m synthetic track, 8 lanes, no lighting; Herkimer St, Bedford-Stuyvesant, Brooklyn
    // NYC public high school; one of the widest free-standing school tracks in Brooklyn
    id: "mock-38",
    reviewSummary: "Currently closed. When it reopens, this will be one of Bed-Stuy's best options — 8 lanes is rare for a public school track in Brooklyn. Expected to reopen Summer 2026.",
    name: "Boys & Girls High School Track",
    lat: 40.6781,
    lon: -73.9314,
    distance: 0.0,
    rating: 1.5,
    reviewCount: 17,
    surface: "Synthetic",
    lanes: 8,
    lighting: false,
    hours: "Currently closed — expected to reopen Summer 2026",
    publicHours: "Currently closed. Expected to reopen Summer 2026. Check back before visiting.",
    publicAccessType: "closed",
    access: "private",
    cost: "Free",
    tags: ["400m", "synthetic", "8-lane", "no lighting", "public school", "Bed-Stuy", "Brooklyn", "closed", "reopening Summer 2026"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/grand-street-campus-field + NYC DOE
    // 400m synthetic track, 6 lanes, confirmed lighting; Stagg St, Williamsburg, Brooklyn
    // Shared multi-school athletic campus in Williamsburg; NYC public school facility
    id: "mock-39",
    reviewSummary: "A lit 6-lane synthetic track in Williamsburg shared by multiple school programs at the Grand Street Campus. The lighting is a genuine advantage over most comparable school tracks in the area, and the Williamsburg location makes it one of the more accessible options in North Brooklyn. Weekend mornings are the most reliably open window.",
    name: "Grand Street Campus Track",
    lat: 40.7106,
    lon: -73.9387,
    distance: 0.0,
    rating: 3.7,
    reviewCount: 22,
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. Shared NYC public school campus — gate may be open evenings and weekends outside of school programming. Lighting is available. Avoid weekday afternoons and mornings during the school year. No formal open-track policy.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "floodlit", "public school", "Williamsburg", "Brooklyn", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/south-shore-high-school + NYC DOE
    // 400m synthetic track, 6 lanes; 732 E 78th St, Canarsie, Brooklyn 11236
    // NYC public high school in Canarsie; one of the few tracks in southeast Brooklyn
    id: "mock-40",
    reviewSummary: "One of the better options for runners in Canarsie and East Flatbush — a proper 6-lane 400m track at a NYC public high school. Access is informal but locals report the gate is reliably open on weekend mornings. No confirmed lighting, so plan for daytime. A practical choice for anyone living in the southeast Brooklyn pocket.",
    name: "South Shore High School Track",
    lat: 40.6348,
    lon: -73.9163,
    distance: 0.0,
    rating: 3.5,
    reviewCount: 12,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no official open-track policy. Avoid weekday afternoons during the school year. Call ahead if making a dedicated trip.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "public school", "Canarsie", "Brooklyn", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/john-dewey-high-school + NYC DOE
    // 400m synthetic track, 6 lanes; 64 Ave X, Gravesend, Brooklyn 11223
    // NYC public high school in Gravesend near Coney Island; track in consistent use by local runners
    id: "mock-41",
    reviewSummary: "A 6-lane synthetic track in Gravesend serving the Coney Island and Brighton Beach running community. Access outside of school hours is informal but commonly reported as problem-free on weekends. One of the few decent tracks in the southern tip of Brooklyn, making it well worth the visit for locals without easy access to Kaiser Park or Abraham Lincoln.",
    name: "John Dewey High School Track",
    lat: 40.5882,
    lon: -73.9796,
    distance: 0.0,
    rating: 3.6,
    reviewCount: 14,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no official open-track policy. Avoid weekday afternoons during the school year when athletic programs are active.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "public school", "Gravesend", "Brooklyn", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/francis-lewis-high-school + NYC DOE
    // Synthetic track, 6 lanes; 173-21 Booth Memorial Ave, Fresh Meadows, Queens 11365
    // NYC public high school in Fresh Meadows; one of the largest high schools in Queens
    id: "mock-42",
    reviewSummary: "A 6-lane synthetic track at one of Queens' larger public high schools, serving runners in Fresh Meadows and Flushing who don't want to trek to Forest Park or Roy Wilkins. Community access on evenings and weekends is informally established — locals report few issues. No confirmed lighting, so plan for daylight hours.",
    name: "Francis Lewis High School Track",
    lat: 40.7412,
    lon: -73.7962,
    distance: 0.0,
    rating: 3.6,
    reviewCount: 11,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open after school hours and on weekends, but there is no official open-track policy. Avoid weekday afternoons during the school year. Check before making a dedicated trip.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["synthetic", "6-lane", "public school", "Fresh Meadows", "Queens", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/springfield-gardens-high-school + NYC DOE
    // 400m synthetic track, 6 lanes, no lighting; Springfield Blvd, Laurelton, Queens 11413
    // NYC public high school in Springfield Gardens/Laurelton; serves SE Queens community
    id: "mock-43",
    reviewSummary: "A 6-lane outdoor track serving the Springfield Gardens and Laurelton community — a part of Queens with limited publicly accessible track options. The 400m synthetic oval is in usable condition and the gate is reported as often open on weekends. No lighting, so early morning or midday visits are the only realistic option.",
    name: "Springfield Gardens High School Track",
    lat: 40.6697,
    lon: -73.7573,
    distance: 0.0,
    rating: 3.4,
    reviewCount: 9,
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no formal open-track policy. No lighting — daytime visits only. Avoid weekday afternoons during the school year.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "no lighting", "public school", "Springfield Gardens", "Queens", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/andrew-jackson-high-school + NYC DOE
    // Synthetic track, 6 lanes; Francis Lewis Blvd, Cambria Heights/Bellaire, Queens 11411
    // NYC public high school serving Cambria Heights, one of the outermost Queens neighborhoods
    id: "mock-44",
    reviewSummary: "A functional 6-lane track at the far southeast edge of Queens — the nearest option for Cambria Heights and Rosedale runners who'd otherwise have to travel to Roy Wilkins or Springfield Gardens. Access is informal and unverified, but public school community use outside school hours is commonly reported. Worth a quick check before visiting.",
    name: "Andrew Jackson High School Track",
    lat: 40.6994,
    lon: -73.7466,
    distance: 0.0,
    rating: 3.4,
    reviewCount: 8,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no formal open-track policy. Avoid weekday afternoons during the school year when athletic programs are active.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["synthetic", "6-lane", "public school", "Cambria Heights", "Queens", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/forest-hills-high-school + NYC DOE
    // Synthetic track, 5 lanes; 67th Rd, Forest Hills, Queens 11375
    // NYC public high school in Forest Hills — serves the Forest Hills / Rego Park running community
    id: "mock-45",
    reviewSummary: "A 5-lane synthetic oval in the heart of Forest Hills, serving a neighborhood that has plenty of runners but few dedicated track options. Access outside of school hours is commonly reported by locals who use it for morning speed workouts. The surface is functional, and the Forest Hills location means nearby amenities are plentiful.",
    name: "Forest Hills High School Track",
    lat: 40.7303,
    lon: -73.8434,
    distance: 0.0,
    rating: 3.5,
    reviewCount: 13,
    surface: "Synthetic",
    lanes: 5,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no formal open-track policy. Avoid weekday afternoons during the school year. Useful for Forest Hills and Rego Park locals.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["synthetic", "5-lane", "public school", "Forest Hills", "Queens", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/bayside-fields (Bayside High School) + NYC DOE
    // Synthetic track; 32-24 Corporal Kennedy St, Bayside, Queens 11361
    // NYC public high school in Bayside; recently received a new field renovation
    id: "mock-46",
    reviewSummary: "A freshly renovated track in Bayside at one of Queens' larger public high schools. Bayside runners have been using this outside of school hours for years with few reported issues. The Corporal Kennedy St location puts it close to Little Neck Parkway and the LIRR Port Washington line, making it accessible from a wide swath of northeast Queens.",
    name: "Bayside High School Track",
    lat: 40.7720,
    lon: -73.7851,
    distance: 0.0,
    rating: 3.7,
    reviewCount: 16,
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open after school hours and on weekends, but there is no official open-track policy. Avoid weekday afternoons during the school year. Recently renovated field.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["synthetic", "public school", "Bayside", "Queens", "unconfirmed access", "renovated"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/bronx-high-school (Harry S. Truman HS) + NYC DOE
    // 400m synthetic track, 5 lanes; Donizetti Place, Co-op City, Bronx 10475
    // NYC public high school in Co-op City; one of few tracks in the far northeast Bronx
    id: "mock-48",
    reviewSummary: "Co-op City's only realistic track option — a 5-lane synthetic oval at Harry S. Truman High School. Runners living in the 55,000-person Co-op City complex frequently use this outside of school hours, and access on weekends has been reported as consistently problem-free. No lighting and somewhat removed from the rest of the Bronx track scene.",
    name: "Harry S. Truman High School Track",
    lat: 40.8741,
    lon: -73.8306,
    distance: 0.0,
    rating: 3.5,
    reviewCount: 14,
    surface: "Synthetic",
    lanes: 5,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open after school hours and on weekends, but there is no official open-track policy. Avoid weekday afternoons during the school year. Serves the Co-op City community.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "5-lane", "public school", "Co-op City", "Bronx", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/susan-e-wagner-high-school + NYC DOE
    // 400m synthetic track, 5 lanes; Manor Rd, Travis/Richmond area, Staten Island 10314
    // NYC public high school; serves the central/mid-island running community
    id: "mock-49",
    reviewSummary: "A 5-lane synthetic track in the mid-island area of Staten Island, useful for runners between the North Shore and the South Shore who find Ocean Breeze or Corporal Thompson too far. Community access outside school hours is informally established. No confirmed lighting — plan for daylight visits.",
    name: "Susan E. Wagner High School Track",
    lat: 40.5975,
    lon: -74.1269,
    distance: 0.0,
    rating: 3.4,
    reviewCount: 10,
    surface: "Synthetic",
    lanes: 5,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate is often open outside of school hours, but there is no formal open-track policy. Avoid weekday afternoons during the school year when athletic programs are active.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "5-lane", "public school", "Staten Island", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/staten-island-technical-high-school + NYC DOE
    // Synthetic track, 6 lanes; 205 10th St, New Dorp, Staten Island 10306
    // NYC public specialized high school (specialized exam school); New Dorp neighborhood
    id: "mock-51",
    reviewSummary: "A 6-lane synthetic track at one of Staten Island's specialized public high schools, near the New Dorp commercial strip. Community runners use this outside of school hours, though it can be harder to access than a general high school given the specialized campus environment. Weekend mornings before 9 am tend to be the most reliably open window.",
    name: "Staten Island Technical High School Track",
    lat: 40.5678,
    lon: -74.1178,
    distance: 0.0,
    rating: 3.5,
    reviewCount: 9,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Unconfirmed — likely accessible evenings & weekends",
    publicHours: "Public access unconfirmed. As a NYC public school, the gate may be open outside of school hours, but there is no formal open-track policy. Weekend mornings before 9 am are reportedly the most reliably open window. Avoid weekday afternoons during the school year.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["synthetic", "6-lane", "public school", "New Dorp", "Staten Island", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },

  {
    // Source: Community report (Reddit r/NYCrunning) + Dashing Whippets event booking
    // Jacob K. Javits Athletic Field at George Washington High School, 549 Audubon Ave, Washington Heights, Manhattan 10040
    // New synthetic track facility confirmed complete; Dashing Whippets track club has hosted meets here
    // Gate was open to a community visitor; no official public access policy published as of May 2026
    id: "mock-52",
    reviewSummary: "A brand-new synthetic track at George Washington High School's Jacob K. Javits Athletic Field — one of the nicest facilities in Washington Heights. The Dashing Whippets running club has already hosted track meets here, which is a strong signal of legitimate access. A community visitor found the gate open with no one stopping entry. There's no official public access policy yet, so treat it as conditional: go, but be prepared to leave if a school event is taking over.",
    name: "George Washington HS — Jacob K. Javits Athletic Field",
    lat: 40.8501,
    lon: -73.9346,
    distance: 0.0,
    rating: 4.0,
    reviewCount: 6,
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: "Unconfirmed — gate reported open; used by running clubs",
    publicHours: "No official public access policy as of May 2026. Community reports indicate the gate is open outside of school programming and the facility is in use by local running clubs including the Dashing Whippets. Avoid weekday afternoons during the school year. Go early on weekends for the best chance of undisrupted access.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "8-lane", "public school", "Washington Heights", "Manhattan", "new facility", "Dashing Whippets", "unconfirmed access"],
    osmType: "way",
    osmId: 0,
  },

  // ── College tracks with conditional public access ──

  {
    // Source: Queens College Athletics + CUNY Athletics + runtrack.run
    // 400m synthetic track on the Queens College campus (CUNY), Flushing, Queens
    // Limited public access Mon–Fri mornings only; groups must reserve through Athletic Dept.
    // Track closes for home meets, holidays, and college activities — call ahead: 718-997-2774
    id: "mock-19",
    reviewSummary: "A solid 8-lane college track in Flushing, but access is tightly managed. The Mon–Fri 7–11 am public window is narrow and the track closes frequently for team events with minimal notice. Runners who can work within those constraints find a well-maintained surface; those with unpredictable schedules will find it frustrating.",
    name: "Queens College Track",
    lat: 40.73636,
    lon: -73.82220,
    distance: 0.0,
    rating: 3.9,
    reviewCount: 34,
    surface: "Synthetic",
    lanes: 8,
    lighting: true,
    hours: "Mon–Fri 7 am – 11 am (public window only)",
    publicHours: "Open to the public Mon–Fri 7 am–11 am only. Groups must reserve in advance through the Queens College Athletic Dept. Track closes for home meets, college events, and holidays — always call ahead: 718-997-2774. No public access on weekends.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free during public hours",
    tags: ["400m", "synthetic", "8-lane", "CUNY", "college", "Flushing", "Queens", "restricted hours"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: Columbia University Athletics + Baker Athletics Complex + Northern Manhattan community program
    // 400m, 8-lane lit track at Wien Stadium — Columbia's Baker Athletics Complex in Inwood, Manhattan
    // Open to Northern Manhattan community residents during limited early-morning windows
    // Max 20 participants at a time; running only — no other field activities permitted
    id: "mock-20",
    reviewSummary: "A Division I stadium track that runners describe as genuinely spectacular — 8 wide lanes, an excellent surface, and a grandstand setting that feels like a real competition venue. The Northern Manhattan community access program is generous for a private university, but hours are now more limited than before and change week to week. Always check the Columbia Athletics website before visiting or you may arrive to find it unavailable.",
    name: "Columbia Baker Athletics Complex (Wien Stadium)",
    lat: 40.87325,
    lon: -73.91648,
    distance: 0.0,
    rating: 3.8,
    reviewCount: 41,
    surface: "Synthetic",
    lanes: 8,
    lighting: true,
    hours: "Variable — check Columbia Athletics website before every visit",
    publicHours: "Community access hours are now more limited and change weekly — do not rely on any fixed schedule. Check the Columbia Athletics website before every visit. Running only, max 20 participants. No public access on weekends.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free (community program)",
    tags: ["400m", "synthetic", "8-lane", "floodlit", "college", "Columbia", "Inwood", "Manhattan", "community program", "restricted hours", "check before visiting"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/wagner-college-stadium + Wagner College Athletics
    // 400m synthetic track, 6 lanes; 606 Howard Ave, Grymes Hill, Staten Island 10301
    // Private liberal arts college; track access status unconfirmed but community use reported
    id: "mock-52",
    reviewSummary: "Wagner College's 6-lane track sits at one of the most scenic spots in all five boroughs — Grymes Hill, with views stretching to New Jersey and Lower Manhattan. Community runners report informal weekend access, though there is no official policy. The uphill approach on Howard Ave is a workout in itself. Worth a call to Athletics before making the trip.",
    name: "Wagner College Stadium Track",
    lat: 40.6175,
    lon: -74.0949,
    distance: 0.0,
    rating: 3.6,
    reviewCount: 13,
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: "Unconfirmed — possibly accessible non-college hours",
    publicHours: "Public access unconfirmed. Private college campus — access is at the college's discretion outside of team schedules. Community use on weekends has been reported. Call Wagner College Athletics before visiting: (718) 390-3227. Avoid days with home meets or team practice.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "college", "private", "Grymes Hill", "Staten Island", "unconfirmed access", "scenic views"],
    osmType: "way",
    osmId: 0,
  },
  {
    // Source: runtrack.run/track/queensborough-community-college + CUNY
    // 400m, 6-lane lit track at Queensborough Community College (QCC), Bayside, Queens
    // Public access during non-class hours — verify with QCC Athletics before visiting
    id: "mock-22",
    reviewSummary: "A well-lit 6-lane track in Bayside that offers genuine training value when accessible. The biggest frustration is the absence of any public-facing access policy — runners must call ahead every visit and hope for availability. Those who get on find the surface in good condition; those who don't find the process opaque.",
    name: "Queensborough Community College Track",
    lat: 40.75483,
    lon: -73.75877,
    distance: 0.0,
    rating: 3.8,
    reviewCount: 19,
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: "Varies — check with QCC Athletics",
    publicHours: "Community access available during non-class, non-practice hours. Public access policy not formally published — call QCC Athletics to confirm current availability before visiting: 718-631-6347. Hours are most reliably open on weekday mornings before 9 am when the campus is less active.",
    publicAccessType: "conditional",
    access: "yes",
    cost: "Free",
    tags: ["400m", "synthetic", "6-lane", "floodlit", "CUNY", "college", "Bayside", "Queens", "restricted hours"],
    osmType: "way",
    osmId: 0,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    trackId: "mock-1",
    author: "Marcus T.",
    avatarInitials: "MT",
    rating: 5,
    date: "2025-04-12",
    body: "Best track in NYC, no question. Mondo surface is fast and in perfect condition. Icahn is a gem — feels like a real stadium even during open sessions.",
  },
  {
    id: "r2",
    trackId: "mock-1",
    author: "Priya S.",
    avatarInitials: "PS",
    rating: 5,
    date: "2025-03-28",
    body: "Came here for a speed workout and was blown away. 8 full lanes, accurate markings, and the lighting is great for evening sessions.",
  },
  {
    id: "r3",
    trackId: "mock-1",
    author: "Jake R.",
    avatarInitials: "JR",
    rating: 4,
    date: "2025-02-14",
    body: "Getting there from Manhattan requires a bus or a long walk from the subway, but the quality makes it worth the trip.",
  },
  {
    id: "r4",
    trackId: "mock-2",
    author: "Aaliyah K.",
    avatarInitials: "AK",
    rating: 5,
    date: "2025-04-01",
    body: "Riverbank is totally underrated. Rooftop location above the highway means no traffic noise, the surface is in great shape, and it's almost never overcrowded.",
  },
  {
    id: "r5",
    trackId: "mock-2",
    author: "Derek M.",
    avatarInitials: "DM",
    rating: 4,
    date: "2025-01-19",
    body: "Solid track. Views of the Hudson are a nice bonus. Sometimes the wind picks up but overall this is one of my regular spots.",
  },
  {
    id: "r6",
    trackId: "mock-4",
    author: "Sofia R.",
    avatarInitials: "SR",
    rating: 4,
    date: "2025-03-15",
    body: "McCarren is super convenient if you're in Williamsburg. Well maintained rubber surface and the lights mean you can go after work. Can get busy on weekends.",
  },
  {
    id: "r7",
    trackId: "mock-4",
    author: "Chris B.",
    avatarInitials: "CB",
    rating: 4,
    date: "2025-02-20",
    body: "Really nice community vibe here. Track is in good shape and there's usually a good mix of serious runners and casual joggers.",
  },
  {
    id: "r8",
    trackId: "mock-7",
    author: "Terrence O.",
    avatarInitials: "TO",
    rating: 4,
    date: "2025-05-03",
    body: "Van Cortlandt is a hidden gem for the Bronx. The WPA-era grandstands give it real character, and the surface is solid. No lights though, so plan for daytime sessions.",
  },
  {
    id: "r9",
    trackId: "mock-7",
    author: "Lauren H.",
    avatarInitials: "LH",
    rating: 4,
    date: "2025-03-11",
    body: "Great place to do a track workout when you're already in the park for cross country trails. Never too crowded and the surface is in decent shape.",
  },
  {
    id: "r10",
    trackId: "mock-9",
    author: "Darnell W.",
    avatarInitials: "DW",
    rating: 5,
    date: "2025-04-18",
    body: "Roy Wilkins is the best track in Southeast Queens. 8 lanes, lights on until 9, and almost always available. The surface is in great condition.",
  },
  {
    id: "r11",
    trackId: "mock-9",
    author: "Keisha M.",
    avatarInitials: "KM",
    rating: 4,
    date: "2025-02-28",
    body: "Convenient for anyone in Jamaica or St. Albans. I come here twice a week after work. The lights make it completely doable even in winter.",
  },
  {
    id: "r12",
    trackId: "mock-12",
    author: "Brendan F.",
    avatarInitials: "BF",
    rating: 5,
    date: "2025-04-22",
    body: "Ocean Breeze is legitimately world-class. The Mondo surface and banking on the turns make it feel like you're running faster. $25 for a whole year is an insane deal.",
  },
  {
    id: "r13",
    trackId: "mock-12",
    author: "Simone A.",
    avatarInitials: "SA",
    rating: 5,
    date: "2025-03-07",
    body: "The only indoor track in NYC that's open to the general public. Perfect for winter training. 8 lanes, Mondo surface, and the staff are really helpful.",
  },
  {
    id: "r14",
    trackId: "mock-11",
    author: "Rashida P.",
    avatarInitials: "RP",
    rating: 4,
    date: "2025-04-05",
    body: "Wingate is super accessible off the 2 train. The 320m length is a bit unusual — I just count 5 laps as 1600m in my head. Great neighborhood track.",
  },
  {
    id: "r15",
    trackId: "mock-13",
    author: "Victor N.",
    avatarInitials: "VN",
    rating: 5,
    date: "2025-04-30",
    body: "The Armory is the best $10 you'll spend in NYC. Mondo surface, banked turns, and world records have been set on this track. Open laps are usually available on weekday mornings.",
  },
  {
    id: "r16",
    trackId: "mock-13",
    author: "Amara J.",
    avatarInitials: "AJ",
    rating: 5,
    date: "2025-03-22",
    body: "Came here for my first indoor workout and I'm hooked. The track is immaculate and the atmosphere — surrounded by all those records on the wall — is genuinely motivating.",
  },
  {
    id: "r17",
    trackId: "mock-14",
    author: "Darius W.",
    avatarInitials: "DW",
    rating: 5,
    date: "2025-05-10",
    body: "The Oval is a Bronx institution. Running inside an old reservoir feels surreal. 4 lanes isn't a ton of room but the community here is great — always a handful of runners out.",
  },
  {
    id: "r18",
    trackId: "mock-14",
    author: "Keisha M.",
    avatarInitials: "KM",
    rating: 4,
    date: "2025-04-03",
    body: "Love this track. Synthetic surface is in decent shape and it's free. The historic setting makes every workout feel a bit special. Get there early on weekends.",
  },
  {
    id: "r19",
    trackId: "mock-15",
    author: "Sasha M.",
    avatarInitials: "SM",
    rating: 4,
    date: "2025-05-08",
    body: "Best free track in Manhattan, full stop. Easy to get to on the 6 train and almost always a few other runners out. Great spot for East Harlem locals and anyone crossing from Randalls Island.",
  },
  {
    id: "r20",
    trackId: "mock-15",
    author: "Andre T.",
    avatarInitials: "AT",
    rating: 4,
    date: "2025-04-20",
    body: "Solid track, clean surface, and right on the East River. It's not flashy but it gets the job done. Parking nearby is a nightmare so take the train.",
  },
  {
    id: "r21",
    trackId: "mock-16",
    author: "Claudia R.",
    avatarInitials: "CR",
    rating: 5,
    date: "2025-05-01",
    body: "The rebuilt track at Juniper Valley is stunning. Brand new surface, clearly marked lanes, and the surrounding park is beautiful. Middle Village doesn't get enough love as a running destination.",
  },
  {
    id: "r22",
    trackId: "mock-16",
    author: "Omar N.",
    avatarInitials: "ON",
    rating: 4,
    date: "2025-04-10",
    body: "Came out from Ridgewood and the J/Z is an easy shot. 6 lanes, barely anyone here on a weekday afternoon. The 2022 rebuild really shows — surface is bouncy and fast.",
  },
  {
    id: "r23",
    trackId: "mock-17",
    author: "Tiana F.",
    avatarInitials: "TF",
    rating: 4,
    date: "2025-04-28",
    body: "Underrated Brownsville gem. Small 4-lane track but it's clean, free, and never crowded. Great for intervals when you don't want to deal with packed parks elsewhere.",
  },
  {
    id: "r24",
    trackId: "mock-17",
    author: "Devon B.",
    avatarInitials: "DB",
    rating: 4,
    date: "2025-03-15",
    body: "Consistent surface, no cost, and an easy walk from the 3 train. Doesn't look like much from the outside but does the job. Wish there were lights for evening runs.",
  },
  {
    id: "r25",
    trackId: "mock-18",
    author: "Yvonne P.",
    avatarInitials: "YP",
    rating: 5,
    date: "2025-05-05",
    body: "Hidden treasure in the northeast Bronx. Mondo surface, 8 full lanes, and it's basically empty on weekday mornings. The setting inside Pelham Bay Park is gorgeous — trees all around.",
  },
  {
    id: "r26",
    trackId: "mock-18",
    author: "Carlos D.",
    avatarInitials: "CD",
    rating: 5,
    date: "2025-04-19",
    body: "This is the best free track in the city that nobody talks about. Competition-grade Mondo, great condition, field event equipment on the outside. Worth the trip out to the 6 train terminus.",
  },
  {
    id: "r35",
    trackId: "mock-23",
    author: "Tony V.",
    avatarInitials: "TV",
    rating: 4,
    date: "2025-05-09",
    body: "Grew up near Tottenville and have been using this track on weekend mornings for years. Gate is almost always open on Saturdays. Surface is solid and the location at the southern tip of the island means it's usually just a handful of locals out there.",
  },
  {
    id: "r36",
    trackId: "mock-23",
    author: "Diana F.",
    avatarInitials: "DF",
    rating: 3,
    date: "2025-03-28",
    body: "Showed up on a Tuesday evening and the gate was open with no issues. But I've also had it be locked on a Saturday morning for an event. No real consistency — call first if you're coming from far away.",
  },
  {
    id: "r37",
    trackId: "mock-24",
    author: "Marco E.",
    avatarInitials: "ME",
    rating: 4,
    date: "2025-04-19",
    body: "Used this track a few Sunday mornings with no one around and no issues. 6 proper lanes, lights work, surface is in good shape. Just keep a low profile and be respectful — you're technically a guest.",
  },
  {
    id: "r38",
    trackId: "mock-24",
    author: "Patricia O.",
    avatarInitials: "PO",
    rating: 3,
    date: "2025-02-10",
    body: "The track itself is great — lit, 6 lanes, real oval. Access is hit or miss. I've been waved off by staff twice on weekday afternoons. Weekend mornings before 9 am have been my sweet spot.",
  },
  {
    id: "r39",
    trackId: "mock-25",
    author: "Evan S.",
    avatarInitials: "ES",
    rating: 4,
    date: "2025-05-14",
    body: "8 lanes at a high school track — I was not expecting that. Found it open on a Sunday afternoon with the gates unlocked. Surface is a bit worn in the inner lanes but totally runnable. Best free multi-lane option in central SI.",
  },
  {
    id: "r40",
    trackId: "mock-25",
    author: "Rosa M.",
    avatarInitials: "RM",
    rating: 3,
    date: "2025-04-02",
    body: "Decent track but no lights so evenings are out. I've always found it open on weekend mornings. It's not flashy but the 8 lanes give you room to breathe, which you can't say about most school tracks.",
  },
  {
    id: "r27",
    trackId: "mock-19",
    author: "Mei L.",
    avatarInitials: "ML",
    rating: 4,
    date: "2025-05-06",
    body: "The 7am window works perfectly for me before my commute. Surface is in good condition and it's almost always quiet at that hour. Just don't show up without calling first — I've been turned away on a meet day.",
  },
  {
    id: "r28",
    trackId: "mock-19",
    author: "Rasheed O.",
    avatarInitials: "RO",
    rating: 4,
    date: "2025-03-19",
    body: "Solid 8-lane track and easy off the 7 train. The restricted hours are annoying but if you can make the morning window it's a genuinely good track. Closed more often than I'd like due to team events.",
  },
  {
    id: "r29",
    trackId: "mock-20",
    author: "Gabriela S.",
    avatarInitials: "GS",
    rating: 5,
    date: "2025-05-12",
    body: "Wien Stadium is spectacular. Running on a real Division I college track with 8 full lanes for free is something I never expected to find in upper Manhattan. The early morning light through the grandstands is beautiful.",
  },
  {
    id: "r30",
    trackId: "mock-20",
    author: "James P.",
    avatarInitials: "JP",
    rating: 4,
    date: "2025-04-14",
    body: "Columbia's community access program is an underrated gem. Yes, the hours are tight and you have to check the website every week, but when it's open it's genuinely one of the best tracks in the borough.",
  },
  {
    id: "r33",
    trackId: "mock-22",
    author: "Fiona C.",
    avatarInitials: "FC",
    rating: 4,
    date: "2025-04-30",
    body: "Nice 6-lane track in Bayside. I called ahead and they let me in no problem on a Tuesday morning. The surface is well-maintained and it's usually quiet. Worth a call before making the trip.",
  },
  {
    id: "r34",
    trackId: "mock-22",
    author: "Leonard A.",
    avatarInitials: "LA",
    rating: 3,
    date: "2025-03-22",
    body: "The track itself is decent but QCC's access policy is completely opaque. No info on their website — you just have to call and hope. When I got access the surface was in good shape and the lights work great.",
  },
];

export function getTrackById(id: string): Track | undefined {
  return MOCK_TRACKS.find((t) => t.id === id);
}

export function getReviewsForTrack(trackId: string): Review[] {
  return MOCK_REVIEWS.filter((r) => r.trackId === trackId);
}
