import type { Track } from "./types";

export const PHILLY_TRACKS: Track[] = [
  {
    id: "philly-1",
    name: "South Philadelphia Super Site",
    lat: 39.912633,
    lon: -75.166231,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Philadelphia Parks & Recreation community track in South Philly. 8-lane synthetic surface built as part of the city's supersite athletic complex program.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Check PPR schedule for open community hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "South Philadelphia", "PPR", "community track", "8 lanes"],
  },
  {
    id: "philly-2",
    name: "Marcus Foster Memorial Stadium",
    lat: 40.017089,
    lon: -75.152923,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track in Nicetown, North Philadelphia. Named after the Oakland school superintendent. Community access likely outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school/athletic hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "North Philadelphia", "Nicetown", "lit", "school track"],
  },
  {
    id: "philly-3",
    name: "Thomas Alva Edison High School Track",
    lat: 40.007,
    lon: -75.143,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Community-accessible track in Franklinville, North Philly. Visitor reports confirm it's open to the public with a relaxed atmosphere and natural tree cover.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Reported open to public; verify hours with school",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "North Philadelphia", "Franklinville", "school track", "community"],
  },
  {
    id: "philly-4",
    name: "Roxborough High School Track",
    lat: 40.035219,
    lon: -75.223632,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track in the Roxborough neighborhood in Northwest Philly. Public access reported during non-school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Roxborough", "Northwest Philadelphia", "lit", "school track"],
  },
  {
    id: "philly-5",
    name: "McCarthy Stadium (La Salle University)",
    lat: 40.037211,
    lon: -75.154009,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "La Salle University's stadium track in Germantown. 6-lane synthetic surface on a university campus.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Check with La Salle University for community access",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Germantown", "La Salle", "university track"],
  },
  {
    id: "philly-6",
    name: "Paul Hines Track",
    lat: 40.063582,
    lon: -75.206625,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Chestnut Hill near West Springfield Avenue. Public access has been reported.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside scheduled events",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Chestnut Hill", "Northwest Philadelphia"],
  },
  {
    id: "philly-7",
    name: "Benjamin Rush High School Track",
    lat: 40.081479,
    lon: -74.972932,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in the Far Northeast, near Milbrook. One of the easternmost tracks in Philadelphia.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Northeast Philadelphia", "Milbrook", "school track"],
  },
  {
    id: "philly-8",
    name: "Abraham Lincoln High School Track",
    lat: 40.043763,
    lon: -75.038464,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track in Holmesburg, Far Northeast Philadelphia. Community access reported outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Northeast Philadelphia", "Holmesburg", "lit", "school track"],
  },
  {
    id: "philly-9",
    name: "Germantown Supersite Track",
    lat: 40.070082,
    lon: -75.173203,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Philadelphia Parks & Recreation supersite synthetic track in Mount Pleasant, Germantown. Community athletic facility.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Check PPR schedule for open community hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Germantown", "Mount Pleasant", "PPR", "community track"],
  },
  {
    id: "philly-10",
    name: "Sweeney Field",
    lat: 39.994643,
    lon: -75.236609,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Highly-rated lit synthetic track in Wynnefield. One of the better community tracks in West Philly — well-maintained with lighting.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open during park hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Wynnefield", "West Philadelphia", "lit", "great condition"],
  },
  {
    id: "philly-11",
    name: "Temple Sports Complex Track",
    lat: 39.973462,
    lon: -75.157458,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track at Temple University's sports complex on North 13th Street. University facility with possible community access.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Check with Temple University for community access hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "North Philadelphia", "Temple University", "university track", "lit"],
  },
  {
    id: "philly-12",
    name: "Franklin Field (University of Pennsylvania)",
    lat: 39.949957,
    lon: -75.189787,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Historic UPenn stadium track in University City, host of the Penn Relays. Public access has been reported during non-event periods.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Check with UPenn for public access windows",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "University City", "West Philadelphia", "UPenn", "historic", "Penn Relays"],
  },
  {
    id: "philly-13",
    name: "Lower Merion High School Track",
    lat: 40.007191,
    lon: -75.278677,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "State-of-the-art synthetic track in Narberth, Lower Merion. Well-known for community access — visitors have praised its condition. Closes during school team practices. Kobe Bryant's alma mater.",
    surface: "Synthetic",
    lanes: 8,
    lighting: false,
    hours: null,
    publicHours: "Open to community outside school athletic events; closes during team practices",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Lower Merion", "Narberth", "Main Line", "community track", "8 lanes", "no lighting"],
  },
  {
    id: "philly-14",
    name: "Memorial Field (Abington Township)",
    lat: 40.113640,
    lon: -75.117686,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track at Abington Township's Memorial Field on Huntingdon Road. Community athletic facility with reported public access.",
    surface: "Synthetic",
    lanes: 5,
    lighting: true,
    hours: null,
    publicHours: "Likely open during park hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Abington", "Montgomery County", "suburban Philadelphia", "lit", "community track"],
  },
  {
    id: "philly-15",
    name: "Ridley High School Track",
    lat: 39.888626,
    lon: -75.334642,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track in Ridley Township, Delaware County. Public access reported outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Ridley Township", "Delaware County", "lit", "school track"],
  },
  {
    id: "philly-16",
    name: "Cheltenham High School Track",
    lat: 40.088220,
    lon: -75.162371,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Cheltenham Township, Montgomery County. Public access reported outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Cheltenham", "Montgomery County", "school track", "no lighting"],
  },
  {
    id: "philly-17",
    name: "Cherry Hill East High School Track",
    lat: 39.873724,
    lon: -74.963054,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track across the river in Cherry Hill, NJ. One of two Cherry Hill high school tracks.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Cherry Hill", "New Jersey", "Camden County", "school track", "no lighting"],
  },
  {
    id: "philly-18",
    name: "Cherry Hill West High School Track",
    lat: 39.925120,
    lon: -75.023526,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at Cherry Hill West, just across the Delaware from Philadelphia. Public access reported outside school hours.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Cherry Hill", "New Jersey", "Camden County", "school track"],
  },
  {
    id: "philly-19",
    name: "Springfield High School Track (Delaware County)",
    lat: 39.928247,
    lon: -75.336359,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Springfield Township, Delaware County. Public access reported outside school hours.",
    surface: "Synthetic",
    lanes: 4,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Springfield", "Delaware County", "school track"],
  },
  {
    id: "philly-20",
    name: "Springfield Township High School Track (Montgomery County)",
    lat: 40.100479,
    lon: -75.196778,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Wyndmoor, Springfield Township, Montgomery County. Public access reported outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Springfield Township", "Wyndmoor", "Montgomery County", "school track"],
  },
  {
    id: "philly-21",
    name: "Bensalem High School Track",
    lat: 40.112113,
    lon: -74.925831,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track in Bensalem, Bucks County. Public access reported outside school hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Bensalem", "Bucks County", "school track", "8 lanes", "no lighting"],
  },
];
