import type { Track } from "./types";

export const PHILLY_TRACKS: Track[] = [
  // ── CITY OF PHILADELPHIA ──────────────────────────────────────────────────
  {
    id: "philly-1",
    name: "South Philadelphia Supersite",
    lat: 39.912633,
    lon: -75.166231,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Philadelphia Parks & Recreation community track at 10th and Bigler in South Philly. Built to be shared among schools without a track.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Weekdays 6am–2:15pm",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Philadelphia", "South Philadelphia", "PPR", "community track", "8 lanes"],
  },
  {
    id: "philly-2",
    name: "Marcus Foster Memorial Stadium",
    lat: 40.017089,
    lon: -75.152923,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Named after educator Marcus Foster, this lit track is in Hunting Park, North Philadelphia. Open to the public dawn to dusk outside school team use.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "North Philadelphia", "Hunting Park", "lit", "school track"],
  },
  {
    id: "philly-3",
    name: "Thomas Edison High School Track",
    lat: 40.0122,
    lon: -75.1291,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Track on the campus of Thomas Edison High School in Franklinville, North Philadelphia. Public access hours unlisted — confirm with school.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Access unlisted — call ahead to confirm",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "North Philadelphia", "Franklinville", "school track"],
  },
  {
    id: "philly-4",
    name: "Roxborough High School Track",
    lat: 40.035219,
    lon: -75.223632,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track at Roxborough High School in Northwest Philadelphia. Open dawn to dusk when not in use by school teams.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Roxborough", "Northwest Philadelphia", "lit", "school track"],
  },
  {
    id: "philly-5",
    name: "Wetzler Track (La Salle University)",
    lat: 40.0338,
    lon: -75.1700,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "La Salle University track on West Olney Avenue, open to residents of the 19138, 19141, and 19144 zip codes. Dawn to dusk outside school team use.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams (restricted to nearby zip codes 19138/19141/19144)",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Olney", "North Philadelphia", "La Salle University", "zip code restricted"],
  },
  {
    id: "philly-6",
    name: "Paul Hines Track (Springside Chestnut Hill Academy)",
    lat: 40.063582,
    lon: -75.206625,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Named after legendary local coach Paul Hines, this synthetic track sits on the Springside Chestnut Hill Academy campus. Open dawn to dusk outside school team use.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Chestnut Hill", "Northwest Philadelphia", "school track"],
  },
  {
    id: "philly-7",
    name: "Benjamin Rush High School Track",
    lat: 40.081479,
    lon: -74.972932,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Track on the campus of Benjamin Rush High School in the Far Northeast. Open dawn to dusk when school teams aren't using it.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Northeast Philadelphia", "school track"],
  },
  {
    id: "philly-8",
    name: "Abraham Lincoln High School Track",
    lat: 40.043763,
    lon: -75.038464,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track in Holmesburg, Far Northeast Philadelphia. Community access reported outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Northeast Philadelphia", "Holmesburg", "lit", "school track"],
  },
  {
    id: "philly-9",
    name: "Germantown Supersite Track",
    lat: 40.07008,
    lon: -75.17320,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Philadelphia PPR community supersite at East Gorgas Lane, built to be shared among Germantown-area schools without a track. Open to all dawn to dusk.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Germantown", "PPR", "community track"],
  },
  {
    id: "philly-10",
    name: "Sean Sweeney Field (St. Joseph's University)",
    lat: 39.994643,
    lon: -75.236609,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Historic home to Saint Joseph's varsity teams at 5600 City Avenue. Seats 3,000 — community access dawn to dusk outside school team use.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Wynnefield", "West Philadelphia", "St. Joseph's University", "lit"],
  },
  {
    id: "philly-11",
    name: "Temple Sports Complex Track",
    lat: 39.973462,
    lon: -75.157458,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Community-accessible track at Temple University's sports complex at 13th and Broad. Ideal for run club meetups. Specific public windows only.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Mon–Fri: 5–7:30am and 6–11pm; Sat–Sun: 5–8am and 5–10pm",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "North Philadelphia", "Temple University", "university track", "lit"],
  },
  {
    id: "philly-12",
    name: "Franklin Field (University of Pennsylvania)",
    lat: 39.949957,
    lon: -75.189787,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Iconic home of the Penn Relays since 1895 in University City. Access limited to eligible users (Penn students, faculty, alumni) during specific windows.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "Weekdays: 7–9am, 11am–2pm, 4–7pm (eligible users only — see Penn recreation site)",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "University City", "West Philadelphia", "UPenn", "historic", "Penn Relays"],
  },
  {
    id: "philly-13",
    name: "Lower Merion High School Track",
    lat: 40.007191,
    lon: -75.278677,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "State-of-the-art synthetic track in Narberth, Lower Merion. Well-known for community access. Closes during team practices. Kobe Bryant's alma mater.",
    surface: "Synthetic",
    lanes: 8,
    lighting: false,
    hours: null,
    publicHours: "Open to community outside school athletic events; closes during team practices",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Lower Merion", "Narberth", "Main Line", "community track", "8 lanes", "no lighting"],
  },
  {
    id: "philly-14",
    name: "Memorial Field (Abington Township)",
    lat: 40.113640,
    lon: -75.117686,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track at Abington Township's Memorial Field. Community athletic facility with public access.",
    surface: "Synthetic",
    lanes: 5,
    lighting: true,
    hours: null,
    publicHours: "Likely open during park hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Abington", "Montgomery County", "suburban Philadelphia", "lit", "community track"],
  },
  {
    id: "philly-15",
    name: "Ridley High School Track",
    lat: 39.888626,
    lon: -75.334642,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Lit synthetic track in Ridley Township, Delaware County. Public access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: true,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Ridley Township", "Delaware County", "lit", "school track"],
  },
  {
    id: "philly-16",
    name: "Cheltenham High School Track",
    lat: 40.088220,
    lon: -75.162371,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Cheltenham Township, Montgomery County. Public access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Cheltenham", "Montgomery County", "school track", "no lighting"],
  },
  {
    id: "philly-17",
    name: "Cherry Hill East High School Track",
    lat: 39.873724,
    lon: -74.963054,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Cherry Hill, NJ — a quick hop across the Delaware from South Philly.",
    surface: "Synthetic",
    lanes: 6,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Cherry Hill", "New Jersey", "Camden County", "school track", "no lighting"],
  },
  {
    id: "philly-18",
    name: "Cherry Hill West High School Track",
    lat: 39.925120,
    lon: -75.023526,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track at Cherry Hill West, across the Delaware from Philadelphia. Public access outside school hours.",
    surface: "Synthetic",
    lanes: null,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Cherry Hill", "New Jersey", "Camden County", "school track"],
  },
  {
    id: "philly-19",
    name: "Springfield High School Track (Delaware County)",
    lat: 39.928247,
    lon: -75.336359,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Springfield Township, Delaware County. Public access outside school hours.",
    surface: "Synthetic",
    lanes: 4,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Springfield", "Delaware County", "school track"],
  },
  {
    id: "philly-20",
    name: "Springfield Township High School Track (Montgomery County)",
    lat: 40.100479,
    lon: -75.196778,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Synthetic track in Wyndmoor, Springfield Township, Montgomery County. Public access outside school hours.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Springfield Township", "Wyndmoor", "Montgomery County", "school track"],
  },
  {
    id: "philly-21",
    name: "Bensalem High School Track",
    lat: 40.112113,
    lon: -74.925831,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "8-lane synthetic track in Bensalem, Bucks County. Public access outside school hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: false,
    hours: null,
    publicHours: "Likely open outside school hours",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Bensalem", "Bucks County", "school track", "8 lanes", "no lighting"],
  },
  // ── SECOND PASS — confirmed via Philly Running Alliance ─────────────────
  {
    id: "philly-22",
    name: "Northeast High School Track",
    lat: 40.057165,
    lon: -75.068067,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Track at Northeast High School (Charles Martin Memorial Stadium) in Rhawnhurst. One of the few city tracks with confirmed daytime public hours.",
    surface: "Synthetic",
    lanes: 8,
    lighting: null,
    hours: null,
    publicHours: "5am–5pm daily",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Northeast Philadelphia", "Rhawnhurst", "8 lanes", "school track"],
  },
  {
    id: "philly-23",
    name: "Penn Charter Track",
    lat: 40.022121,
    lon: -75.184730,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "9-lane synthetic track on the campus of William Penn Charter School in East Falls. Confirmed community access dawn to dusk outside school team use.",
    surface: "Synthetic",
    lanes: 9,
    lighting: null,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "East Falls", "Northwest Philadelphia", "9 lanes", "school track"],
  },
  {
    id: "philly-24",
    name: "Greenawalt Track (Germantown Friends School)",
    lat: 40.0452,
    lon: -75.1915,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Resurfaced in blue and orange in 2020, this track was gifted to Germantown Friends School by the Greenawalt family in 2003. Located at the same Midvale Ave complex as the PPR supersite.",
    surface: "Synthetic",
    lanes: 6,
    lighting: null,
    hours: null,
    publicHours: "Dawn to dusk, except when in use by school teams",
    publicAccessType: "conditional",
    access: "permissive",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Germantown", "Germantown Friends School", "school track"],
  },
  {
    id: "philly-25",
    name: "Corporal Jimmy O'Connor Track",
    lat: 40.0828,
    lon: -74.9743,
    rating: 0,
    reviewCount: 0,
    reviewSummary: "Fully public Philadelphia Parks & Recreation track in Fox Chase, Northeast Philly. One of the most accessible tracks in the city — open daily with generous hours.",
    surface: "Synthetic",
    lanes: null,
    lighting: true,
    hours: null,
    publicHours: "Daily 9am–9pm",
    publicAccessType: "open",
    access: "public",
    cost: null,
    tags: ["synthetic", "Philadelphia", "Northeast Philadelphia", "Fox Chase", "PPR", "public", "lit", "community track"],
  },
];
